### PR TITLE
finished splash page

### PR DESCRIPTION
**Pull request by mchen892**
#### What is the purpose of your change?
- I completed the splash page 

#### What areas of the application does this change impact? (changes API, folder structure, etc)
- folder structure and added files

#### What features/fixes are deferred/not handled in this PR?
- the title/button moves with the background (need assistance here).

## Checklist
- [ ] Adds unit tests
- [ ] Has a work item linked to the PR

### CODE REVIEW

**Comment by mchen892** [comment]
check the latest commit (i fixed deployment)

**Comment by michachan** [comment]
Waiting on lint issues to be resolved.

https://app.netlify.com/sites/survival-guide/deploys/64d7f9a1627060000832488a

**Review by michachan — CHANGES_REQUESTED** [review]
Linting

**Review by mchen892 — COMMENTED** [review]
New commit that fixes linting @michachan

**Review by michachan — APPROVED** [review]

**Pull request closed without merging**
